//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsModelNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int PersonID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Patronymic { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string AcademicGroupNumber { get; set; }
        public string PhotoURL { get; set; }
        public string Skills { get; set; }
        public string TEMA_DIPLOMA { get; set; }
    }
}
